#if !canImport(ObjectiveC)
import XCTest

extension Swift_ISO8601_DurationParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Swift_ISO8601_DurationParserTests = [
        ("testFullStringParsedCorrectly", testFullStringParsedCorrectly),
        ("testIndividualDaysParsedCorrectly", testIndividualDaysParsedCorrectly),
        ("testIndividualHoursParsedCorrectly", testIndividualHoursParsedCorrectly),
        ("testIndividualMinutesParsedCorrectly", testIndividualMinutesParsedCorrectly),
        ("testIndividualMonthsParsedCorrectly", testIndividualMonthsParsedCorrectly),
        ("testIndividualSecondsParsedCorrectly", testIndividualSecondsParsedCorrectly),
        ("testIndividualYearsParsedCorrectly", testIndividualYearsParsedCorrectly),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(Swift_ISO8601_DurationParserTests.__allTests__Swift_ISO8601_DurationParserTests),
    ]
}
#endif
